# Generated by Django 6.0 on 2025-12-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'verbose_name': 'Перелёт', 'verbose_name_plural': 'Перелёты'},
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_time',
            field=models.TimeField(default='12:00', verbose_name='Время прилёта'),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(default='10:00', verbose_name='Время вылета'),
        ),
    ]
